services:

  app:
    build: .
    container_name: langchain_app
    restart: always
    depends_on:
      - pgvector
    ports:
      - "8081:8000"
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      DATABASE_URL: postgresql://postgres:postgres@pgvector:5432/ragdb
      HOST: 0.0.0.0
      PORT: 8000
    volumes:
      - .:/app

  pgvector:
    image: pgvector/pgvector:pg16
    container_name: pgvector_db
    restart: always
    environment:
      POSTGRES_DB: ragdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5544:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: